### ISSUE TITLE
Video tool still missing

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#104]
Please fix it, so we can do Data Quality Check on this, too

**Comment by mmagaldi-eng** [comment]
@vittorianovancini, please add in a comment some URLs of the videos that don't work.

**Comment by vittorianovancini** [comment]
Well, right now, not even one of the video I tried did give any result. The last one I tried, which is without doubt computer generated, is https://www.youtube.com/watch?v=TSV98UqKhi4&feature=youtu.be. This is a Youtube video, so it should not have any complications. I've tried it with other online tools and it seems to work fine. Tomorrow I'll try again with other videos.

**Comment by pstalidis** [comment]
The service is working.
Service missing / not working / working with errors, are different things, especially when reporting an issue.

That being said, there was a wrong call from the UI to the API. This problem has been fixed. If other problems occur please report them in a new issue.

**Comment by vittorianovancini** [comment]
?Thanks! Sorry for the bad terminology!

________________________________
Da: Panagiotis Stalidis <notifications@github.com>
Inviato: martedì 9 febbraio 2021 12:48
A: fandangOrg/fandango
Cc: Vancini Vittoriano; Mention
Oggetto: Re: [fandangOrg/fandango] Video tool still missing (#104)


The service is working.
Service missing / not working / working with errors, are different things, especially when reporting an issue.

That being said, there was a wrong call from the UI to the API. This problem has been fixed. If other problems occur please report them in a new issue.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FfandangOrg%2Ffandango%2Fissues%2F104%23issuecomment-775881543&e=c9024bf9&h=4173f068&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI7AQP3MKZGQYTWXBWQ7KSLS6EOJVANCNFSM4XJNXTYA&e=c9024bf9&h=53680a74&f=n&p=y>.

________________________________

Il contenuto di questa e-mail è rivolto unicamente alle persone alle quali è indirizzato; le relative informazioni sono da considerarsi strettamente riservate e tutelate ai sensi del Regolamento UE 2016/679 (GDPR) per la Protezione dei Dati Personali, nonché del D. Lgs. n. 196/2003 e successive modifiche. Sono vietati la riproduzione, la diffusione e l'uso di questa e-mail in mancanza di autorizzazione del destinatario. In caso di ricezione della presente e-mail per errore, si prega di non diffonderla, di informare immediatamente il mittente e di eliminarne ogni copia. Le opinioni espresse in questa e-mail appartengono esclusivamente al mittente e potrebbero non riflettere necessariamente quelle dell'Agenzia ANSA.

The content of this e-mail is only addressed to the people to whom it is addressed; the relevant information has to be considered as confidential and protected under the Regulation EU 2016/679 (GDPR), General Data Protection Regulation, as well as the Legislative Decree 196/2003 and subsequent amendments. The reproduction, distribution and use of this e-mail in the absence of the recipient's authorization is forbidden. If you receive this e-mail by mistake, please do not disseminate it, inform the sender immediately and delete any copies. The opinions expressed in this message belong to sender alone and may not necessarily reflect those of ANSA AGENCY.

________________________________
